name: Deploy Static Site on AWS

on:
  push:
    branches:
      - main
      - prod

jobs:
  lint-and-validate:
    uses: ./.github/workflows/lint-and-validate.yml
    name: Lint & Validate Terraform
    secrets:
      DOCKER_HUB_USER: ${{vars.DOCKER_HUB_USER}}
      DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [lint-and-validate]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set variables
        run: |
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
              echo "prod" > .workspace
          else
              echo "staging" > .workspace
          fi
      - name: Push to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.eu-west-1.amazonaws.com
          docker build --compress -t ${{vars.ECR_REPO_STATIC_SITE}}:$GITHUB_SHA .
          docker push ${{vars.ECR_REPO_STATIC_SITE}}:$GITHUB_SHA
      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          export TF_VAR_ecr_static_site_image="${{ vars.ECR_REPO_STATIC_SITE }}:$GITHUB_SHA"
          workspace=$(cat .workspace)
          cd infra/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy/ workspace select -or-create $workspace
          docker compose run --rm terraform -chdir=deploy/ apply -auto-approve
